---
title: "Presentacion"
author: "Pao"
date: "September 23, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(metR)
library(rvad)
library(data.table)
library(magrittr)
library(ggplot2)
library(dplyr)
library(patchwork)
source("helpfun.R")


# Variables útiles
mapa.ar <- setDT(fortify(rnaturalearth::ne_states(country = c("Argentina")))) %>% 
   .[, .(long = approx(.I, long, n = .N*5)$y,
         lat = approx(.I, lat, n = .N*5)$y),
     by = .(group)] %>%
   .[, range := rrange(long, lat)] %>%
   .[, azimuth := azimuth(long, lat)] %>%
   .[, group2 := cuad_split(azimuth), by = group]
```

## Campos de dBZ y Vr

```{r read}
volumen <- ReadNetCDF("data/cfrad.20181121_110832.0000_to_20181121_111113.0000_RMA4_0200_02.nc",
                      vars = c("Vda", "TH", "azimuth", "elevation")) %>% 
  setDT() %>% 
  setnames(colnames(.), c("range", "radial_wind", "time", "dBZ", "azimuth", "elevation"))
```

```{r dbz}
na.omit(volumen) %>% 
  .[elevation == unique(elevation)[1]] %>% 
  ggplot(aes(azimuth, range/1000)) +
  geom_point(aes(color = dBZ, size = range)) +
  scale_size_area(max_size = 0.1) +
  scale_color_gradientn(colors = viridisLite::turbo(n = 7)) +
  geom_path(data = mapa.ar,
            aes(group = interaction(group, group2)), color = "darkgray") +
  scale_x_continuous(name = NULL, labels = NULL, breaks = seq(0, 359, 90)) +
  scale_y_continuous(name = "Distancia al centro (km)",
                     breaks = c(40, 80, 120, 160, 200),
                     limits = c(0, 200), expand = c(0, 0)) +
  guides(size = "none") +
  labs(title = "RMA4 - Resistencia", 
       subtitle = "Tiempo: 2018-11-21 11:00:00 Z | Elevación 0.53 grados") + 
  coord_polar() +
  theme_minimal(base_size = 16)+ 
  theme(panel.ontop = T, 
        legend.key.height = unit(3, "lines"),
        legend.key.width = unit(0.4, "cm"))

ggsave("Rplot03.png", units = "cm", width = 20, height = 17)

```

```{r}
na.omit(volumen) %>% 
  .[elevation == unique(elevation)[1]] %>% 
  ggplot(aes(azimuth, range/1000)) +
  geom_point(aes(color = radial_wind, size = range)) +
  scale_size_area(max_size = 0.1) +
  scale_color_divergent(name = "Vr", limits = c(-20, 20), oob = scales::squish) +
  geom_path(data = mapa.ar,
            aes(group = interaction(group, group2)), color = "darkgray") +
  scale_x_continuous(name = NULL, labels = NULL, breaks = seq(0, 359, 90)) +
  scale_y_continuous(name = "Distancia al centro (km)",
                     breaks = c(40, 80, 120, 160, 200),
                     limits = c(0, 200), expand = c(0, 0)) +
  guides(size = "none") +
  labs(title = "RMA4 - Resistencia", 
       subtitle = "Tiempo: 2018-11-21 11:00:00 Z | Elevación 0.53 grados") + 
  coord_polar() +
  theme_minimal(base_size = 16)+ 
  theme(panel.ontop = T, 
        legend.key.height = unit(3, "lines"),
        legend.key.width = unit(0.4, "cm"))  

ggsave("Rplot04.png", units = "cm", width = 20, height = 17)
```

```{r}
na.omit(volumen) %>% 
  .[elevation == unique(elevation)[1] & range == 54990] %>% 
  ggplot(aes(azimuth, radial_wind)) +
  geom_line() +
  geom_smooth(method = "lm", formula = y ~ I(sin(x*pi/180)) + I(cos(x*pi/180)), 
              se = F, color = "#562457") +
  scale_y_continuous(name = "Velocidad radial (m/s)") +
  scale_x_continuous(name = "Azimut (grados)") +
  geom_hline(yintercept = 0) +
  theme_minimal()
```

```{r}
VAD <- with(volumen, vad_fit(radial_wind, azimuth, range, elevation, outlier_threshold = 3)) %>% setDT %>% 
  .[, spd := sqrt(u^2 + v^2)]

VAD %>% 
  ggplot(aes(spd, height)) +
  geom_point(aes(color = factor(elevation))) +
  scale_color_viridis_d(name = "Elevación") +
  coord_cartesian(ylim = c(0, 2000)) +
  labs(x = "Velocidad m/s", y = "Altura (m)") +
  theme_minimal()

ggsave("Rplot02.png", units = "cm", width = 10, height = 12)
```

```{r validación}
radial_wind <- ReadNetCDF("data/cfrad.20181121_110832.0000_to_20181121_111113.0000_RMA4_0200_02.nc", vars = c("Vda", "azimuth", "elevation")) 
  
VAD <- with(radial_wind, vad_fit(Vda, azimuth, range, elevation, r2 = 0.5)) %>% 
  setDT() %>% 
  .[, `:=`(spd = sqrt(u^2 + v^2))]

soundings <- fread("data/soundings_wyoming_87155.csv") %>% 
  .[, time := as_datetime(time)] %>% 
  .[time  == as_datetime("20181121120000")]

VAD %>% 
  copy() %>% 
  .[r2 > 0.8] %>%
  # .[elevation %between% c(0, 1)] %>% 
  .[, vad_regrid(.SD, layer_width = 50, ht_out = seq(100, 2000, 50))] %>%
  setDT() %>% 
  .[, error := rvad:::error_prop(u, v, u_std.error, v_std.error)] %>% 
  .[, spd := sqrt(u^2 + v^2)] %>% 
  ggplot(aes(height +119, spd)) +
  # geom_ribbon(aes(ymin = mean.spd - sd, ymax = mean.spd + sd), alpha = 0.2) +
  geom_line(color = "#440154") +
  geom_point(color = "#440154") +
  geom_ribbon(aes(ymin = spd - 3*error, ymax = spd + 3*error), fill = "#440154", alpha = 0.5) + 
  geom_line(data = na.omit(soundings), aes(height, spd), color = "#238A8D") +
  geom_point(data = na.omit(soundings), aes(height, spd), color = "#238A8D") +
  coord_flip(ylim = c(0, 15)) +
  labs(x = "Altura", y = "Velocidad") +
  theme_minimal() +

VAD %>% 
  copy() %>% 
  .[r2 > 0.8] %>%
  # .[elevation %between% c(0, 1)] %>% 
  .[, vad_regrid(.SD, layer_width = 50, ht_out = seq(100, 2000, 50))] %>% 
  ggplot(aes(height +119, 180+atan2(u, v)*180/pi)) +
  # geom_ribbon(aes(ymin = mean.spd - sd, ymax = mean.spd + sd), alpha = 0.2) +
  # geom_line(aes(color = QC)) +
  geom_point(color = "#440154") +
  # geom_line(data = na.omit(soundings), aes(height, dir)) +
  geom_point(data = na.omit(soundings), aes(height, dir), color = "#238A8D") +
  coord_flip() +
  labs(x = "Altura", y = "Dirección") +
  theme_minimal() +
  plot_layout(ncol = 2)

```


```{r}

library(rvad)

volumen <- metR::ReadNetCDF("data/RMA4.20181121_110832.0000.nc",
                      vars = c("radial_wind", "azimuth", "elevation")) 
 
VAD <- with(volumen, vad_fit(radial_wind, azimuth, range, elevation, outlier_threshold = 3))

# Argumentos para el control de calidad
max_na = 0.2
max_consecutive_na = 30
r2_min = 0.8
outlier_threshold = Inf
azimuth_origin = 90
azimuth_direction = c("cw", "ccw")

```

```{r}

plot(VAD)

```

```{r}

VAD_regrid <- vad_regrid(VAD, layer_width = 100, ht_out = seq(100, 2000, 50))

# Argumentos para controlar la resolución
layer_width
resolution = layer_width
ht_out = NULL
min_n = 5

plot(VAD_regrid)

```

